=== lmr97/fd-tnkr/schemata/checklistSubmission.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "slctdChecklistSubmission",
    "description": "Describes structure of shift submitted checklist, showing what was completed, by whom, and when.",
    "type": "object",
    "required": [ "date", "shift", "employee", "sections" ],
    "properties": {
        "date": { "type": "string", "format": "date" },
        "employee": { "type": "string" },
        "shift": { "$ref": "./checklistDefs.schema.json#/$defs/shift" },
        "sections": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [ "startBy", "dueBy", "listItems" ],
                "properties": {
                    "startBy": { "$ref": "./checklistDefs.schema.json#/$defs/startBy" },
                    "dueBy": { "$ref": "./checklistDefs.schema.json#/$defs/dueBy" },
                    "listItems": {
                        "description": "The tasks that should be completed between `startBy` and `dueBy` times, and whether they were marked `done`.",
                        "type": "array",
                        "items": { 
                            "type": "object",  
                            "properties": {
                                "task": { "type": "string" },
                                "done": { "type": "boolean" }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== lmr97/fd-tnkr/slctd-checklist/submissions/amChecklistSubmission.json
{
    "$schema": "../schemata/checklistSubmission.schema.json",
    "date": "2026-02-20",
    "employee": "Martin",
    "shift": "AM",
    "sections": [
        {
            "startBy": "07:00:00-07:00",
            "dueBy": "09:00:00-07:00",
            "listItems": [
                {
                    "task": "Fill out occupancy information in Red Book and review any information needing to be passed along.",
                    "done": false
                },
                {
                    "task": "Count your drawer, and ensure it is at correct amount before beginning your shift. Ensure the drawer is balanced before the NA shift departs.",
                    "done": false
                },
                {
                    "task": "Login to GXP and review “All GXP Open Cases.”  Communicate with night auditor on any open or “In Progress” cases in GXP to ensure timely response and completion.",
                    "done": false
                },
                {
                    "task": "Check hotel's Gmail inbox (towneplacesuitesslc@gmail.com PW:slctd84101) for outstanding emails that require attention",
                    "done": false
                },
                {
                    "task": "Print the Contingency Reports: (F8-FOffice-Reports-Contingency Reports).",
                    "done": false
                },
                {
                    "task": "Straighten up the Lobby and wipe down the tables when it's necessary",
                    "done": false
                },
                {
                    "task": "Between 8:00AM-8:30AM - Call Red Hanger if guest laundry needs to be picked up.",
                    "done": false
                },
                {
                    "task": "Review your availability (F8-Rsrv-R-V).",
                    "done": false
                },
                {
                    "task": "Print Arrivals Report (F8-Rsrv-P-A-F10) in order to block rooms for the arriving Ambassador, Titanium, Platinum, Gold, and Silver guests.  Block remaining arrivals for today. (NOTE: MAKE SURE TO BLOCK GUESTS STAYING THROUGH THE WEEKEND ON THE EAST FACING SIDE TO AVOID MUSIC FROM SURROUNDING NIGHT CLUBS).",
                    "done": false
                },
                {
                    "task": "Add in company names for those with corporate rates.",
                    "done": false
                },
                {
                    "task": "Check for duplicate reservations (F8-Rsrv-P-D-Enter-F10) and keep them blocked in same room if it's available. Notify the Housekeeping Manager and/or Supervisor to clean as a “Stayover”.",
                    "done": false
                },
                {
                    "task": "Continuously monitor FOSSE home screen for any “Process Mobile” and “Process GuestRequest” alerts.  Prepare, complete and respond to all requests for Mobile Check-In and Mobile Requests in a timely manner.",
                    "done": false
                },
                {
                    "task": "Print PrePay Report (F8-FOffice-P-P) Ensure we have credit card payment for all guests.",
                    "done": false
                },
                {
                    "task": "Check credit cards for additional authorization. (F8-BOffice-C-C-Y-Enter-F4-Y-Enter) and notify guests as needed to update their account.",
                    "done": false
                },
                {
                    "task": "Print the credit card exception report (F8-BOffice-C-E-Y-Enter-Enter). Search for any declined credit cards and resolve.",
                    "done": false
                },
                {
                    "task": "Review any Out of Order rooms/maintenance requests that are pending and update in FOSSE.",
                    "done": false
                },
                {
                    "task": "Check the arrival report for non-member, then record their names on the Redbook table.",
                    "done": false
                }
            ]
        },
        {
            "startBy": "09:00:00-07:00",
            "dueBy": "11:00:00-07:00",
            "listItems": [
                {
                    "task": "Check for Internet Advance Deposit Reservations (F8-Rsrv-A-Q) (only if there are any reservations) *Important: This will take a minute to generate. Clear report Y/N? Hit N.    To post the advance deposit - Go into reservation of each guest - O – D – N. Charge the applicable credit card for the dollar amount provided. Hit F10. The amount of the advance deposit will appear in the Account Detail box at top right on Adv Deposit. Ensure there is a ‘D7’ in the special request field for incidental folio.  Clear from report Y/N? Hit yes if amount has been posted and appears in the account detail box.",
                    "done": false
                },
                {
                    "task": "Print the Contingency Reports: (F8-FOffice-Reports-Contingency Reports).",
                    "done": false
                },
                {
                    "task": "Update MARSHA Interface Status. (F8-Rsrv-M-D). Make sure that MARSHA interface is running properly. You can tell by the cursor moving automatically through the sections. If it seems to be frozen or not responding properly, call PMS Support at 240-632-6000 Option 1-2-2 and ask for help. When done checking, hit “E” to get out of this screen.",
                    "done": false
                },
                {
                    "task": "Sign in to the DLZ and complete Daily Learning Questions on the home screen",
                    "done": false
                },
                {
                    "task": "Sign in to the DLZ: click on TRAINING and work on completing recommended and/or required training (Best practice: spend 15-30 minutes per shift, or as time allows)",
                    "done": false
                },
                {
                    "task": "Read and respond to any training emails from AGM",
                    "done": false
                },
                {
                    "task": "Restock and arrange the back office storage with all guest amenities.",
                    "done": false
                },
                {
                    "task": "Organize the In-A-Pinch storage area.",
                    "done": false
                }
            ]
        },
        {
            "startBy": "11:00:00-07:00",
            "dueBy": "14:30:00-07:00",
            "listItems": [
                {
                    "task": "Print departure list and verify with housekeeping that all scheduled departures have vacated the room and then check the guest out in FOSSE",
                    "done": false
                },
                {
                    "task": "Check Credit Card Authorization Binder for today's date and update reservations with correct method of payment.",
                    "done": false
                },
                {
                    "task": "Refresh Coffee & Water Station.",
                    "done": false
                },
                {
                    "task": "Clean and Sanitized the Key Cards",
                    "done": false
                },
                {
                    "task": "Complete Bucket Check (F8-FOffice-F-B). Check credit card number, address, company name, departure date, and rate are all correct.",
                    "done": false
                },
                {
                    "task": "Stock In a Pinch Market and take out any expired items.  Give all expired items to AGM.",
                    "done": false
                },
                {
                    "task": "Print Discrepancies (F8-RoomMgt-H-P-D-5-Enter-Enter) and resolve with Housekeeping.",
                    "done": false
                },
                {
                    "task": "Verify any Unexpected Stayovers (F8-RoomMgt-H-P-U).",
                    "done": false
                },
                {
                    "task": "Clean and straighten up Front Desk area. Wipe down monitor screens and counters.",
                    "done": false
                },
                {
                    "task": "Log all incoming packages and notify in-house guests.",
                    "done": false
                },
                {
                    "task": "PARKING PASSES: Collect parking passes from garage (Send maintenance with the key if you can't leave the desk) and reconcile all passes due back",
                    "done": false
                }
            ]
        },
        {
            "startBy": "14:30:00-07:00",
            "dueBy": "15:00:00-07:00",
            "listItems": [
                {
                    "task": "Count your cash to determine if a drop is needed. Wait for the PM shift to count the drawer before departing your shift.",
                    "done": false
                },
                {
                    "task": "Run Shift Closing report BUT DO NOT UPDATE IT YET. (F8-FOffice-C-S, “Option”=P F10). Review amount to drop and review to ensure proper charge codes, and fix if needed so that drop reflects Closing Report.",
                    "done": false
                },
                {
                    "task": "Run Shift Closing reports * Now close out Shift 2 (F8-FOffice-C-S “Option”=U F10, follow prompts to update to next shift).",
                    "done": false
                },
                {
                    "task": "Look at GXP and review “All GXP Open Cases.”  Ensure all cases are either closed or passed on to next shift.",
                    "done": false
                }
            ]
        }
    ]
}
